"use client";
import {useState} from "react";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import {ArrowRight,ArrowUpRight,ChevronLeft,ChevronRight,Pause,Quote,Truck,Anchor,ShoppingBag} from "lucide-react";
const imgs={hero:"https://cdn.prod.website-files.com/69830fbb86d197088c4b8cfc/69aeb2e79d0e158391417e3b_Convoy-Home_poster.0000000.jpg",airplane:"https://cdn.prod.website-files.com/69830fbb86d197088c4b8cfc/69ad68b6f993ccefefa7417d_Blog-4.avif",train:"https://cdn.prod.website-files.com/69830fbb86d197088c4b8cfc/69ad68b6675fc6f54607de28_Blog-6.avif",truck:"https://cdn.prod.website-files.com/69830fbb86d197088c4b8cfc/69ad68b678d176563a6a9329_Blog-2.avif",industry:"https://cdn.prod.website-files.com/69830fbb86d197088c4b8cfc/69af20d7ea4b9315662b4f5b_Industries-1.avif"};
const services=[["Freight & Transportation Management",imgs.truck],["Route Planning & Scheduling",imgs.train],["Logistics Technology Integration",imgs.airplane],["Warehouse & Distribution Strategy",imgs.hero],["Transportation Cost Reduction",imgs.industry]];
const industries=[["Automotive & Transportation",Truck],["Maritime Distribution",Anchor],["E-commerce & Retail",ShoppingBag]];
const testimonials=[["Convoy transformed our logistics operation in six months. Their hands-on approach delivered huge improvements in delivery speed and cost savings that exceeded our expectations.","Jennifer Martinez, VP of Operations","47%","Cost Savings","2.8x","Delivery Speed"],["We were skeptical about consultants, but Convoy proved us wrong. They identified inefficiencies we didn't know existed and helped us implement solutions that actually work in real operations.","Marcus Chen, Director of Supply Chain","35%","Route Optimization","3.1x","Fleet Efficiency"],["The ROI was immediate. Convoy improved our warehouse operations and reduced our freight costs. Their expertise in logistics technology integration was exactly what we needed to scale.","Sarah Johnson, Chief Operations","42%","Warehouse Efficiency","2.6x","Order Processing Speed"]];
function Pill({children}:{children:React.ReactNode}){return <span className="pill">{children}</span>}
function ImgCard({src,title,large=false}:{src:string,title:string,large?:boolean}){return <div className={(large?"gallery-card large":"gallery-card")+" group"}><img src={src} alt="" /><div className="image-shade"/><div className="image-title">{title}</div></div>}
export default function Home(){
 const [industry,setIndustry]=useState(0),[testimonial,setTestimonial]=useState(0); const t=testimonials[testimonial];
 return <main className="overflow-hidden bg-[#e9e9e7] text-[#282828]">
 <Navbar />
 <Hero />
 <section className="logo-strip"><div className="logo-track">{["Loom & Ledger™","Orbitale Net™","Crimson Bay™","Loom & Ledger™","Orbitale Net™","Crimson Bay™"].map((x,i)=><div className="client-logo" key={i}>{x}</div>)}</div></section>
 <section id="about" className="about-section container"><div className="about-inner"><Pill>A BIT ABOUT US</Pill><h2>Convoy was built to bridge the gap between operational execution and business strategy. We provide dependable transportation solutions while helping organizations optimize performance, reduce operational inefficiencies, and scale with confidence.</h2><div className="about-stats"><div><strong>47%</strong><span>Cost Savings</span></div><i/><div><strong>2.8x</strong><span>Delivery Speed</span></div></div></div><div className="gallery-row"><ImgCard src={imgs.airplane} title=""/><ImgCard src={imgs.train} title=""/><ImgCard src={imgs.truck} title=""/><ImgCard src={imgs.airplane} title=""/><ImgCard src={imgs.industry} title=""/></div></section>
 <section id="services" className="services-section"><div className="container"><div className="section-head"><div><Pill>OUR SERVICES</Pill><h2>Logistics & Consulting<br/>Solutions by Convoy©</h2></div><div className="section-side"><p>Convoy combines reliable transportation with expert consulting to streamline operations, reduce costs, and drive growth.</p><div><a className="small-btn dark" href="#contact">Explore Services <ArrowRight size={15}/></a><a className="small-btn pale" href="#contact">Buy Template</a></div></div></div><div className="service-grid">{services.map(([title,src],i)=><ImgCard key={title} src={src} title={title} large={i<2}/>)}</div></div></section>
 <section id="industries" className="industries-section container"><div className="industry-copy"><Pill>INDUSTRIES WE SERVE</Pill><h2>At Convoy© We Proudly<br/>Serve 20+ Industries</h2><div className="industry-buttons"><button className="small-btn dark">All Industries <ArrowRight size={15}/></button><a className="small-btn pale" href="#contact">Buy Template</a></div><div className="industry-list">{industries.map(([name,Icon],i)=><button key={name} onClick={()=>setIndustry(i)} className={industry===i?"active":""}><Icon size={15}/>{name}</button>)}</div></div><div className="industry-feature"><img src={imgs.industry} alt="Industry"/><div className="feature-label"><Pill>LAST-MILE DELIVERY</Pill><div className="feature-stats"><div><strong>52%</strong><span>Faster Fulfillment</span></div><div><strong>3.2x</strong><span>Order Volume Growth</span></div></div></div></div></section>
 <section className="testimonial-section"><div className="container"><div className="testimonial-top"><div><Pill>TESTIMONIALS</Pill><h2>They Tried, Listen<br/>What They Say</h2></div><div className="slider-arrows"><button onClick={()=>setTestimonial((testimonial+testimonials.length-1)%testimonials.length)}><ChevronLeft/></button><button onClick={()=>setTestimonial((testimonial+1)%testimonials.length)}><ChevronRight/></button></div></div><div className="testimonial-card"><div className="quote-copy"><Quote size={34} fill="currentColor"/><p>{t[0]}</p><small>{t[1]}</small><div className="brand">◢ {["Crimson Bay™","Loom & Ledger™","Orbitale Net™"][testimonial]}</div></div><div className="results"><Pill>RESULTS ACHIEVED</Pill><div><strong>{t[2]}</strong><span>{t[3]}</span></div><div><strong>{t[4]}</strong><span>{t[5]}</span></div></div></div></div></section>
 <section id="case-studies" className="case-section container"><div className="case-head"><div><Pill>CASE STUDIES</Pill><h2>Results That Speak<br/>for Themselves</h2></div><p>Suspendisse finibus, elit eu luctus malesuada finibus, elit eu luctus malesuada, urna tortor pharetra risus, in laoreet ipsum.</p></div><div className="case-grid"><div className="case-card"><img src={imgs.truck} alt=""/><span>40% Cost Reduction</span><h3>Reducing Fleet Costs 40% for National Distributor Through Route Optimization</h3><a href="#contact">Read Case Studies <ArrowRight size={15}/></a></div><div className="case-card"><img src={imgs.train} alt=""/><span>52% Faster Fulfillment</span><h3>Cutting Delivery Times in Half for E-Commerce Brand Across United States</h3><a href="#contact">Read Case Studies <ArrowRight size={15}/></a></div></div></section>
 <section id="contact" className="contact-section container"><div className="contact-copy"><Pill>REQUEST A BID</Pill><h2>Are You Interested in Optimizing Your Logistic Operations?</h2><p>Get in Touch, and we will book a meeting with our consultant.</p><div className="consultant"><div className="avatar">AM</div><div><strong>Alex Morgan</strong><span>Senior Consultant</span><span>+48 456 789 006</span><span>ALEX@convoy.com</span></div></div></div><form className="contact-form"><label>Name<input placeholder="John Doe"/></label><label>Email<input placeholder="john@doe.com"/></label><label>Subject<select><option>Type of project</option><option>Freight</option><option>Consulting</option></select></label><label>Your Message<textarea placeholder="Tell us about your project"/></label><label className="check"><input type="checkbox"/> I agree to Privacy Policy.</label><button className="submit">Submit <ArrowRight size={17}/></button></form></section>
 <section className="cta-section"><img src={imgs.hero} alt=""/><div className="cta-overlay"/><div className="cta-content"><Pill>WEBFLOW TEMPLATE</Pill><h2>Ready to build<br/>remarkable website?</h2><div><a className="btn light" href="#contact">Buy Template <ArrowRight size={18}/></a><a className="btn glass" href="#services">All Templates</a></div></div></section>
 <footer className="footer"><div className="container footer-grid"><div><div className="footer-logo">▣ CONVOY©</div><p>Convoy<br/>ul. Ładunku 56,<br/>30-003 Kraków</p><p>+48 456 789 006<br/>hello@convoy.com</p></div><div><h4>COMPANY</h4><a>Home</a><a>About</a><a>Contact</a><a>Legal</a><a>404</a></div><div><h4>CMS PAGES</h4><a>Services</a><a>Service Page (CMS)</a><a>Case Studies</a><a>Case Study (CMS)</a><a>Blog</a><a>Blog Article (CMS)</a></div><div><h4>SOCIAL MEDIA</h4><a>Linkedin</a><a>Facebook</a><a>Instagram</a><a>Tiktok</a></div><div><h4>JOIN NEWSLETTER</h4><div className="newsletter"><input placeholder="hi@convoy.com"/><button>Subscribe</button></div><small>Your information is never disclosed to third parties.</small></div></div><div className="footer-bottom container"><span>© MADE IN 2026 WITH {"{LOVE}"} BY TOWASZE.STUDIO</span><span>POWERED BY WEBFLOW　 CHANGLELOG　 INSTRUCTIONS　 STYLE GUIDE　 LICENSES</span></div></footer></main>
}