import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import {ArrowUpRight} from "lucide-react";
const services=["Freight transportation","Managed transportation","Warehousing & fulfillment","Technology solutions"];
const industries=["Retail","Manufacturing","Food & beverage","Automotive","Consumer goods","Industrial"];
export default function Home(){return <main><Navbar/><Hero/>
<section id="about" className="container py-28 md:py-40"><div className="grid gap-10 md:grid-cols-12"><p className="text-xs uppercase tracking-[.2em] md:col-span-3">01 / About</p><div className="md:col-span-9"><h2 className="display max-w-6xl text-5xl md:text-[7rem]">We make moving freight <span className="text-black/20">simple, efficient and human.</span></h2><p className="mt-10 max-w-2xl text-base leading-7 text-black/60 md:text-lg">A modern logistics partner built around visibility, reliability and technology. We connect shippers, carriers and data to keep goods moving.</p></div></div><div className="mt-20 grid grid-cols-2 gap-px bg-black/10 md:grid-cols-4">{["24/7","99%","50k+","10M+"].map((n,i)=><div className="bg-[#f4f3ef] py-8 md:py-12" key={n}><div className="display text-5xl md:text-7xl">{n}</div><p className="mt-3 text-[10px] uppercase tracking-widest text-black/50">{["Visibility","On-time","Loads moved","Miles tracked"][i]}</p></div>)}</div></section>
<section id="services" className="bg-[#171717] py-28 text-[#f4f3ef] md:py-40"><div className="container"><p className="text-xs uppercase tracking-[.2em] text-white/40">02 / Services</p><h2 className="display mt-6 text-6xl md:text-[9rem]">WHAT WE DO</h2><div className="mt-16 grid gap-px bg-white/15 md:grid-cols-2">{services.map((s,i)=><a href="#contact" key={s} className="group bg-[#171717] p-7 transition hover:bg-white/[.03] md:p-12"><div className="mb-24 text-xs text-white/35">0{i+1}</div><div className="flex items-end justify-between gap-5"><h3 className="display text-3xl md:text-5xl">{s}</h3><span className="rounded-full border border-white/20 p-3 transition group-hover:bg-white group-hover:text-black"><ArrowUpRight size={19}/></span></div></a>)}</div></div></section>
<section id="industries" className="container py-28 md:py-40"><p className="text-xs uppercase tracking-[.2em]">03 / Industries</p><div className="mt-12 grid md:grid-cols-2">{industries.map((x,i)=><div key={x} className="border-b border-black/15 py-7"><div className="flex justify-between"><span className="display text-3xl md:text-5xl">{x}</span><span className="text-xs opacity-40">0{i+1}</span></div></div>)}</div></section>
<section className="bg-[#d8ff3e] py-28 md:py-40"><div className="container"><p className="text-xs uppercase tracking-[.2em]">04 / Testimonials</p><blockquote className="display mt-12 max-w-6xl text-5xl md:text-[7rem]">“The right logistics partner doesn't just move freight. They move the business forward.”</blockquote><div className="mt-14 border-t border-black/20 pt-5 text-xs uppercase tracking-widest">— Operations Director, Global Retailer</div></div></section>
<section id="contact" className="relative overflow-hidden bg-[#171717] py-32 text-[#f4f3ef] md:py-48"><div className="absolute inset-0 opacity-20" style={{backgroundImage:"url(https://images.unsplash.com/photo-1494412651409-8963ce7935a7?auto=format&fit=crop&w=2200&q=80)",backgroundSize:"cover",backgroundPosition:"center"}}/><div className="container relative"><p className="text-xs uppercase tracking-[.2em] text-white/40">05 / Start a conversation</p><h2 className="display mt-8 text-6xl md:text-[9rem]">LET'S MOVE<br/>FORWARD.</h2><a href="mailto:hello@example.com" className="mt-10 inline-flex items-center gap-2 rounded-full bg-[#f4f3ef] px-7 py-4 text-sm font-semibold text-[#171717]">Talk to us <ArrowUpRight size={18}/></a></div></section>
<footer className="bg-[#171717] px-5 pb-8 text-[#f4f3ef] md:px-8"><div className="mx-auto max-w-[1280px] border-t border-white/15 py-10"><div className="display text-4xl">CONVOY<span className="text-sm align-top">®</span></div><p className="mt-4 text-sm text-white/40">Move freight smarter. Grow business faster.</p><div className="mt-14 flex justify-between text-xs text-white/25"><span>© 2026 Convoy</span><span>Built with Next.js</span></div></div></footer></main>}